In [1]:
"""
Numpy
"""
# 다차원 배열(ndarray)을 저장, 처리
#  pip install numpy - 패키지 설치
#  import numpy as np - 패키지 사용하기

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


In [9]:
# Creating a numpy array
list = [1.5, 2.3, 6.4, "string"]

arr = np.array(list)  #값을 직접 입력해도 가능 ex) [1,2,3,4]
print(arr)

['1.5' '2.3' '6.4' 'string']


In [11]:
# .dtype attribute
print(arr.dtype)

<U32


In [16]:
"""
Size Comparison of ndarray and list objects
"""
from sys import getsizeof

lst = [1]
print(getsizeof(lst)) #56 -> 64: int+object meta info

arr = np.array(lst)
print(getsizeof(arr)) #104->108: int(4byte)

64
108


In [18]:
"""
Operation with Numpy Arrays
"""
prices = [30, 25, 40, 20, 20, 35, 50 ,35]

new_prices = [price-5 for price in prices]
print(new_prices)

# with a ndarray
prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [47]:
"""
exrecise 3번의 시험에 대한 각 학생별 점수를 numpy 배열로 선언 (test1, test2, test3)
"""
test1 = np.array([92, 94, 88, 91, 87])
test2 = np.array([79, 100, 86, 93, 91])
test3 = np.array([87, 85, 72, 90, 92])

# +2 at test3
test3_fixed = test3 + 2
print(test3_fixed)

# get total grade of each student
tatal_grade = test1+ test2+ test3
print(tatal_grade)

# get average score
final_grade=tatal_grade/3
print(final_grade)

# get Jeremy's test2 score
jeremy_test2=test2[3]
print(jeremy_test2)

# get first test scores for Manual and Adwoa 
manual_adowa_test1 = np.array([test1[1], test1[2]])
print(manual_adowa_test1)

# save all students score at double lists
student_scores = np.array([test1, test2, test3])
print(student_scores)

# get test3 score of Tanya
print(student_scores[2][0])

# get all scores of Cody 
print(student_scores[:, 4]) # :는 전체

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [36]:
"""
Logical Operation with arrays
"""
# masking
a = np.array([10, 2, 2, 4, 5, 3, 9])
mask = a > 5
print(mask)

# select using Logical operations
selected = a[a > 5]
print(selected)

# combined Logical operations / &
selected = a[(a>6) | (a<4)]
print(selected)

selected = a[(a>4) & (a<8)]
print(selected)


[ True False False False False False  True]
[10  9]
[10  2  2  3  9]
[5]


In [48]:
# exer2
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
print(porridge)

# porridge under 60
cold = porridge[porridge < 60]
print(cold)

# porridge over 80
hot = porridge[porridge > 80]
print(hot)

#  prridge over 60 under 80
just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)

[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
